final List articlesPart1 = [
  "Article 1 : OBJET\n",
  "TarzanExpress est la première application africaine lancée au Togo permettant aux utilisateurs de faire des achats d’articles en gros et en détails en ligne sur les plateformes e-commerce partout dans le monde pour être livrer en Afrique.",
  "\nArticle 2 : DELAIS DE LIVRAISON\n",
  "Nos offres, contrats, commandes et livraisons de marchandises sont soumis aux présentes conditions générales d’utilisation, que l'utilisateur accepte expressément et sans réserve, nonobstant toutes stipulations contraires émanant de nos clients. Nos engagements ne sont valables qu'après acceptation de ces présents termes. Nos propositions de prix ne peuvent constituer une offre dont l'acceptation par l’utilisateur entraînerait formation du contrat que sous réserve de l'accord de notre part sur les conditions d'exécution et de règlement, l’utilisateur devant présenter des garanties jugées suffisantes. En cas de commande sur ordre, le contrat n'est réputé conclu et les approvisionnements déclenchés qu'au moment de la confirmation par l’utilisateur de la date de livraison régissent par les termes de délai de livraison. L’utilisateur dispose d’une entière liberté de choix de commande de marchandises disponible sur toutes les plateformes d’E-commerce. Il devrait suivre la procédure qui lui sera soumis via nos plateformes « TarzanExpress »",
  "\nArticle 3 : TRANSPORT\n",
  "Si vous voulez effectuer une commande via notre application TarzanExpress référez-vous à notre guide d’utilisation.",
];

final List articlesPart2 = [
  "\nArticle 5 : TRANSPORT\n",
  "Le transport des marchandises se fait par voie aérienne et maritime.Les délais de livraison sont spécifiés dans l’Article 4",
  "\nArticle 6 : RECLAMATION\n",
  "Sans préjudice des dispositions à prendre vis-à-vis du transporteur, les réclamations sur les vices apparents ou sur la non-conformité du produit livré ou produit commandé ou au bordereau d'expédition, ne relève pas de notre société. Toutefois un courrier peut leur être adressé en vue d’une réclamation. Les marchandises contestées doivent être stockées en magasin par l'acheteur jusqu'au règlement définitif de la réclamation. L'acheteur ne peut pas refuser de réceptionner des marchandises qui se trouvent dans notre magasin.",
  "\nArticle 7 : COTATION ET FRAIS DE SERVICES\n",
  "Les prix des articles sont émis par les fournisseurs et consultés sur leur site à titre indicatif. Néanmoins TarzanExpress valide  les prix finaux par rapport à la disponibilité des articles auprès des fournisseurs et fournit une cotation au client. La cotation d’une commande prend en compte les prix des articles, les frais de services et les frais de transport.\n\n",
];
final List articlesPart3 = [
  "\nArticle 8 : MODE DE PAIEMENT\n",
  "Toutes les factures sont réglables via mobile money, en paiement espèce, virement bancaire ou chèque bancaire. Notre Société se réserve le droit, à tout moment, même en cours d'exécution d'un marché ou d'une commande, d'exiger une garantie par nous de la bonne exécution des engagements du client. Le défaut ou retard de paiement à une échéance entraîne l'exigibilité immédiate des sommes à régler, y compris celles non échues. Le défaut de paiement à l'échéance ou le défaut d'acceptation quelconque de son envoi pour acceptation nous autorise à suspendre les livraisons, à mettre fin au contrat ou à modifier les conditions de ce contrat, sans préjudice de tous dommages-intérêts.",
  "\nArticle 9 : RESILIATION\n",
  "En cas d'inexécution de la part de l'acheteur d'une ou plusieurs de ses obligations ou de redressement ou de liquidation judiciaire prononcé à son encontre, le vendeur pourra constater la résiliation de la vente de plein droit aux torts de l'acheteur, sur simple lettre recommandée.",
  "\nArticle 10 : FORCE MAJEURE\n",
  "Sont considérés comme cas de force majeure, tous événements indépendants de la volonté de l'une ou l'autre partie ou irrésistibles et extérieurs qui auraient pour effet de perturber la réalisation normale de ses programmes de fabrication, livraisons ou approvisionnements. La partie qui invoquera la force majeure en avisera aussitôt l'autre par tous moyens et l'avertira dans un délai raisonnable pendant lequel elle estime ne pouvoir être en mesure de remplir ses obligations. La partie ainsi affectée sera dispensée, sans avoir à verser une quelconque indemnité, de l'exécution de ses obligations, à l'exception du paiement des produits déjà réceptionnés, et ce tant que les effets de force majeure n'auront cessé. Cette cessation sera notifiée par lettre par la partie qui a notifié le cas de force majeure. Toutefois, si ces effets se prolongent au-delà de SIX mois à compter de la notification du cas de force majeure, les parties se concerteront sur la suite à donner à la commande et sur les aménagements qui s'imposent. Si elles ne parviennent pas à un accord : - si la force majeure est invoquée par l'acheteur, le vendeur aura le droit de résilier le contrat, - si la force majeure est invoquée par le vendeur, l'acheteur aura le droit de résilier le contrat, Une telle résiliation ne peut donner lieu à aucune indemnité.",
  "\nArticle 11 : ATTRIBUTION DE COMPETENCE\n",
  "Les présentes conditions générales de vente et les contrats qu'elles régissent, ainsi que leurs suites, sont soumis au droit togolais en vigueur. Toutefois, la négociation est souhaitable en cas de litige. Les litiges nés de l'application des présentes conditions générales de vente, de la formation du contrat de vente, de son exécution ou de sa fin seront tranchés par le Tribunal de Commerce de Lomé.",
];
